apiVersion: v1
kind: Service
metadata:
  name: auth-http-service
  labels:
    service: auth-http-service
spec:
  type: NodePort
  ports:
    - port: 4002
      targetPort: 4002
      nodePort: 30002
  selector:
    app: auth-http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-http-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-http
  template:
    metadata:
      labels:
        app: auth-http
    spec:
      containers:
        - name: auth-http
          image: auth-http:latest
          imagePullPolicy: Never
          env:
            - name: USER_SECRET
              valueFrom:
                secretKeyRef:
                  name: user.jwt
                  key: privateKey
          ports:
            - containerPort: 4002
