apiVersion: v1
kind: Service
metadata:
  name: auth-micro-service
  labels:
    service: auth-micro-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: auth-micro

  ports:
    - name: grpc
      port: 4003
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-micro-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-micro
  template:
    metadata:
      labels:
        app: auth-micro
    spec:
      containers:
        - name: auth-micro
          image: auth-micro:latest
          ports:
            - containerPort: 4003
